# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sergey Olisov
title: Senior Solution Architect. Developer
email: olisov.sergey@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: sergeyolisov
github_username:  Lefthander
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sergeyolisov
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergey and I'm a senior solution architect. As well as designing complex solutions I also have experience making software and digital hardware. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Openstack</mark> and <mark>Telecom</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
