# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sergey Olisov
title: Senior Solution Architect. Developer
email: olisov.sergey@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: sergeyolisov
github_username:  Lefthander
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sergeyolisov
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergey and I'm a Senior Solution Architect and Developer with over 15 years experience in telecom and 5 years experience in RnD. 

  I am most skilled in: <mark>Solving practical business problems</mark> and <mark>Trobleshooting</mark>

  My fields of interests are:
  
  - <mark>Cloud Technologies</mark>
  - <mark>System Design</mark>
  - <mark>IoT</mark>
  - <mark>Software Development</mark>

  I have experience to work with many programing languages: ​like very specific hardware languages ​​<mark>VHDL</mark>, <mark>Verilog</mark> and specific assemblers for embedded microcontrollers
  and like general purpose languages: <mark>GNU C/C++</mark>,<mark>Watcom C++</mark>,<mark> C#</mark>,<mark> Python</mark> and <mark> Golang </mark>. Last few years I mostly use in my projects the <mark> Golang</mark> language.
  To my great regret I never have been a proffesional programmer, the programming was always a secodnary additional task in my daily work. But from the school time I dream to be a proffecional programmer. :(

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Drawing
   - Gaming
   - Electric guitar
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
darkmode: true
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
